{#
  National-feed cities publish a schedule (and a realtime feed) covering far more than
  the city we score. Zurich's static is the whole Swiss timetable: 5,122 routes, of which
  615 serve canton Zürich.

  [rev 2026-08-25] The allow-list was applied on the REALTIME side only, in Spark
  (silver_normalize.national_filter). The SCHEDULE side had no filter at all, so every
  schedule-derived model — int_gtfs_scheduled_stop_times, int_service_dates' downstream
  joins, int_service_frequency, and above all fct_service_delivery_daily's `scheduled`
  CTE — spanned the entire Swiss network.

  Left alone, Zurich's completeness would have been measured as
  "trips observed on 615 Zurich routes / trips scheduled on 5,122 Swiss routes" —
  roughly a 1-in-8 denominator, reading ~12% and failing every completeness floor for a
  city that is actually working correctly. Zurich went live 2026-08-25 with zero gold
  rows, so this is fixed before any wrong number was ever materialized.

  The filter is a semi-join against the checked-in seed, which is generated by
  scripts/generate_zurich_allowlist.py together with the S3 copy Spark reads — the two
  must never diverge. Cities that are not national feeds are untouched.
#}

{% macro national_allowlist_filter(city_col, route_col) %}
    (
        {{ city_col }} not in ('zurich')
        or {{ route_col }} in (
            select route_id from {{ ref('zurich_route_allowlist') }}
        )
    )
{% endmacro %}
